version: "3.8"

services:
    backup-service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "6969:3000"
        environment:
            - PORT=3000
            - API_KEY=${API_KEY}
            - DATABASE_URL=${DATABASE_URL}
            - R2_BUCKET=${R2_BUCKET}
            - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
            - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
            - R2_ACCOUNT_ID=${R2_ACCOUNT_ID}
        restart: unless-stopped
        # Mount volume for pnpm store to improve rebuild times
        volumes:
            - pnpm-store:/root/.local/share/pnpm/store

volumes:
    pnpm-store:
